// <auto-generated />
namespace _3D_Art_Portfolio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newMigration11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newMigration11));
        
        string IMigrationMetadata.Id
        {
            get { return "202106161228168_newMigration11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
